name: "menu-calculator"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - ${APP_PORT:-3000}:3000
    restart: always
    networks:
      - app-network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_MENU_USR}
      POSTGRES_PASSWORD: ${DB_MENU_PASS}
      POSTGRES_DB: ${DB_MENU_DB}
    ports:
      - ${DB_MENU_PORT:-5432}:5432
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_MENU_USR"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge