name: "menu-calculator"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER=${APP_USER:-1002} 
        - APP_GROUP=${APP_GROUP:-1002}
    environment:
      - DB_MENU_HOST=${DB_MENU_HOST}
      - DB_MENU_PORT=${DB_MENU_PORT}
      - APP_ENV=${APP_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - ${APP_PORT:-3000}:3000
    restart: always
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_MENU_USR}
      POSTGRES_PASSWORD: ${DB_MENU_PASS}
      POSTGRES_DB: ${DB_MENU_DB}
    ports:
      - ${DB_MENU_PORT:-5432}:5432
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_MENU_USR"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge