name: "menu-calculator"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${APP_PORT:-3000}
    environment:
      - ADDRESS=${APP_ADDRESS:-0.0.0.0}
      - PORT=${APP_PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    restart: always
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_MENU_USR}
      - POSTGRES_PASSWORD=${DB_MENU_PASS}
      - POSTGRES_DB=${DB_MENU_DB}
    ports:
      - ${DB_MENU_PORT:-5432}:5432
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT:-16543}:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge